/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAnalysisRouteImport } from './routes/_authed/analysis'
import { Route as AuthedCargaRouteImport } from './routes/_authed/carga'
import { Route as AuthedPlanificacionRouteImport } from './routes/_authed/planificacion'
import { Route as AuthedPlanificacionPointIdRouteImport } from './routes/_authed/planificacion_.$pointId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalysisRoute = AuthedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCargaRoute = AuthedCargaRouteImport.update({
  id: '/carga',
  path: '/carga',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanificacionRoute = AuthedPlanificacionRouteImport.update({
  id: '/planificacion',
  path: '/planificacion',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanificacionPointIdRoute =
  AuthedPlanificacionPointIdRouteImport.update({
    id: '/planificacion_/$pointId',
    path: '/planificacion/$pointId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/analysis': typeof AuthedAnalysisRoute
  '/carga': typeof AuthedCargaRoute
  '/planificacion': typeof AuthedPlanificacionRoute
  '/planificacion/$pointId': typeof AuthedPlanificacionPointIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analysis': typeof AuthedAnalysisRoute
  '/carga': typeof AuthedCargaRoute
  '/planificacion': typeof AuthedPlanificacionRoute
  '/': typeof AuthedIndexRoute
  '/planificacion/$pointId': typeof AuthedPlanificacionPointIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/analysis': typeof AuthedAnalysisRoute
  '/_authed/carga': typeof AuthedCargaRoute
  '/_authed/planificacion': typeof AuthedPlanificacionRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/planificacion_/$pointId': typeof AuthedPlanificacionPointIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analysis'
    | '/carga'
    | '/planificacion'
    | '/planificacion/$pointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analysis'
    | '/carga'
    | '/planificacion'
    | '/'
    | '/planificacion/$pointId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/analysis'
    | '/_authed/carga'
    | '/_authed/planificacion'
    | '/_authed/'
    | '/_authed/planificacion_/$pointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analysis': {
      id: '/_authed/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthedAnalysisRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/carga': {
      id: '/_authed/carga'
      path: '/carga'
      fullPath: '/carga'
      preLoaderRoute: typeof AuthedCargaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planificacion': {
      id: '/_authed/planificacion'
      path: '/planificacion'
      fullPath: '/planificacion'
      preLoaderRoute: typeof AuthedPlanificacionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planificacion_/$pointId': {
      id: '/_authed/planificacion_/$pointId'
      path: '/planificacion/$pointId'
      fullPath: '/planificacion/$pointId'
      preLoaderRoute: typeof AuthedPlanificacionPointIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAnalysisRoute: typeof AuthedAnalysisRoute
  AuthedCargaRoute: typeof AuthedCargaRoute
  AuthedPlanificacionRoute: typeof AuthedPlanificacionRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedPlanificacionPointIdRoute: typeof AuthedPlanificacionPointIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAnalysisRoute: AuthedAnalysisRoute,
  AuthedCargaRoute: AuthedCargaRoute,
  AuthedPlanificacionRoute: AuthedPlanificacionRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPlanificacionPointIdRoute: AuthedPlanificacionPointIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
