/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAnalysisRouteImport } from './routes/_authed/analysis'
import { Route as AuthedCargaRouteImport } from './routes/_authed/carga'
import { Route as AuthedPlanificacionRecursosRouteImport } from './routes/_authed/planificacion.recursos'
import { Route as AuthedPlanificacionRutasRouteImport } from './routes/_authed/planificacion.rutas'
import { Route as AuthedPlanificacionRecursosPointIdRouteImport } from './routes/_authed/planificacion.recursos_.$pointId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalysisRoute = AuthedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCargaRoute = AuthedCargaRouteImport.update({
  id: '/carga',
  path: '/carga',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlanificacionRecursosRoute =
  AuthedPlanificacionRecursosRouteImport.update({
    id: '/planificacion/recursos',
    path: '/planificacion/recursos',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPlanificacionRutasRoute =
  AuthedPlanificacionRutasRouteImport.update({
    id: '/planificacion/rutas',
    path: '/planificacion/rutas',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPlanificacionRecursosPointIdRoute =
  AuthedPlanificacionRecursosPointIdRouteImport.update({
    id: '/planificacion/recursos_/$pointId',
    path: '/planificacion/recursos/$pointId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/analysis': typeof AuthedAnalysisRoute
  '/carga': typeof AuthedCargaRoute
  '/planificacion/recursos': typeof AuthedPlanificacionRecursosRoute
  '/planificacion/rutas': typeof AuthedPlanificacionRutasRoute
  '/planificacion/recursos/$pointId': typeof AuthedPlanificacionRecursosPointIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analysis': typeof AuthedAnalysisRoute
  '/carga': typeof AuthedCargaRoute
  '/': typeof AuthedIndexRoute
  '/planificacion/recursos': typeof AuthedPlanificacionRecursosRoute
  '/planificacion/rutas': typeof AuthedPlanificacionRutasRoute
  '/planificacion/recursos/$pointId': typeof AuthedPlanificacionRecursosPointIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/analysis': typeof AuthedAnalysisRoute
  '/_authed/carga': typeof AuthedCargaRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/planificacion/recursos': typeof AuthedPlanificacionRecursosRoute
  '/_authed/planificacion/rutas': typeof AuthedPlanificacionRutasRoute
  '/_authed/planificacion/recursos_/$pointId': typeof AuthedPlanificacionRecursosPointIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analysis'
    | '/carga'
    | '/planificacion/recursos'
    | '/planificacion/rutas'
    | '/planificacion/recursos/$pointId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analysis'
    | '/carga'
    | '/'
    | '/planificacion/recursos'
    | '/planificacion/rutas'
    | '/planificacion/recursos/$pointId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/analysis'
    | '/_authed/carga'
    | '/_authed/'
    | '/_authed/planificacion/recursos'
    | '/_authed/planificacion/rutas'
    | '/_authed/planificacion/recursos_/$pointId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analysis': {
      id: '/_authed/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthedAnalysisRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/carga': {
      id: '/_authed/carga'
      path: '/carga'
      fullPath: '/carga'
      preLoaderRoute: typeof AuthedCargaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planificacion/recursos': {
      id: '/_authed/planificacion/recursos'
      path: '/planificacion/recursos'
      fullPath: '/planificacion/recursos'
      preLoaderRoute: typeof AuthedPlanificacionRecursosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planificacion/rutas': {
      id: '/_authed/planificacion/rutas'
      path: '/planificacion/rutas'
      fullPath: '/planificacion/rutas'
      preLoaderRoute: typeof AuthedPlanificacionRutasRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/planificacion/recursos_/$pointId': {
      id: '/_authed/planificacion/recursos_/$pointId'
      path: '/planificacion/recursos/$pointId'
      fullPath: '/planificacion/recursos/$pointId'
      preLoaderRoute: typeof AuthedPlanificacionRecursosPointIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAnalysisRoute: typeof AuthedAnalysisRoute
  AuthedCargaRoute: typeof AuthedCargaRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedPlanificacionRecursosRoute: typeof AuthedPlanificacionRecursosRoute
  AuthedPlanificacionRutasRoute: typeof AuthedPlanificacionRutasRoute
  AuthedPlanificacionRecursosPointIdRoute: typeof AuthedPlanificacionRecursosPointIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAnalysisRoute: AuthedAnalysisRoute,
  AuthedCargaRoute: AuthedCargaRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPlanificacionRecursosRoute: AuthedPlanificacionRecursosRoute,
  AuthedPlanificacionRutasRoute: AuthedPlanificacionRutasRoute,
  AuthedPlanificacionRecursosPointIdRoute:
    AuthedPlanificacionRecursosPointIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
